name: Child Workflow

on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
      time:
        required: false
        type: string
        default: "day"

jobs:
  greet:
    runs-on: ubuntu-latest
    outputs:
      greeting-message: ${{ steps.greeting.outputs.message }}
    steps:
      - name: Set greeting message
        id: greeting
        run: |
          if [ "${{ inputs.time }}" = "morning" ]; then
            echo "message=Good morning, ${{ inputs.name }}!" >> $GITHUB_OUTPUT
          elif [ "${{ inputs.time }}" = "evening" ]; then
            echo "message=Good evening, ${{ inputs.name }}!" >> $GITHUB_OUTPUT
          else
            echo "message=Hello, ${{ inputs.name }}!" >> $GITHUB_OUTPUT
          fi

      - name: Display greeting
        run: echo "${{ steps.greeting.outputs.message }}"