name: Child Workflow

on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
      time:
        required: false
        type: string
        default: "day"

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Set greeting message
        id: greeting
        run: |
          if [ "${{ inputs.time }}" = "morning" ]; then
            echo "Good morning, ${{ inputs.name }}!" > greeting.txt
          elif [ "${{ inputs.time }}" = "evening" ]; then
            echo "Good evening, ${{ inputs.name }}!" > greeting.txt
          else
            echo "Hello, ${{ inputs.name }}!" > greeting.txt
          fi
      
      - name: Upload greeting
        uses: actions/upload-artifact@v4
        with:
          name: greeting
          path: greeting.txt